# Generated by Django 3.2 on 2022-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/profileimages/default.jpg', upload_to='media/profileimages')),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('born_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
