# Generated by Django 3.2 on 2022-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_profile_born_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='born_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
